### ISSUE TITLE
casuses rehash to crash if no Gemfile

### ISSUE THREAD

**Issue by daenney** [carsomyr/rbenv-bundler#51]
When issuing `rbenv rehash` when the bundler plugin is installed from a directory that doesn't have a Gemfile a stack trace is printed:

```
/usr/local/var/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/dsl.rb:40:in `rescue in eval_gemfile': There was an error in your Gemfile, and Bundler cannot continue. (Bundler::GemfileError)
	from /usr/local/var/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/dsl.rb:32:in `eval_gemfile'
	from /usr/local/var/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/dsl.rb:10:in `evaluate'
	from /usr/local/var/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/definition.rb:25:in `build'
	from /usr/local/Cellar/rbenv-bundler/0.99/etc/rbenv.d/bundler/rehash.rb:95:in `gemspecs'
	from /usr/local/Cellar/rbenv-bundler/0.99/etc/rbenv.d/bundler/rehash.rb:202:in `block (2 levels) in rehash'
	from /usr/local/Cellar/rbenv-bundler/0.99/etc/rbenv.d/bundler/rehash.rb:190:in `each'
	from /usr/local/Cellar/rbenv-bundler/0.99/etc/rbenv.d/bundler/rehash.rb:190:in `block in rehash'
	from /usr/local/Cellar/rbenv-bundler/0.99/etc/rbenv.d/bundler/rehash.rb:189:in `open'
	from /usr/local/Cellar/rbenv-bundler/0.99/etc/rbenv.d/bundler/rehash.rb:189:in `open'
	from /usr/local/Cellar/rbenv-bundler/0.99/etc/rbenv.d/bundler/rehash.rb:189:in `rehash'
	from /usr/local/Cellar/rbenv-bundler/0.99/etc/rbenv.d/bundler/rehash.rb:470:in `<main>'
```

**Comment by daenney** [comment]
Eh sorry, confusing a few things.
